# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # Git
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, master, --branch, main]
      - id: check-added-large-files
        args: ['--maxkb=100']
      - id: check-merge-conflict
      # Codestyle
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      # Schema validity
      - id: check-yaml
      # Secret leakage
      - id: detect-aws-credentials
      - id: detect-private-key

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.13.0
    hooks:
      - id: check-jsonschema
        name: 'Check GitHub Workflows'
        files: ^\.github/workflows/
        types: [yaml]
        args: ['--schemafile', 'https://json.schemastore.org/github-workflow']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        types_or: [ts]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
      - id: gitleaks
