name: 'Pull Request Labeler'
on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.config.yml
          sync-labels: true
