name: 'Lint PR'

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            chore
          wip: true
          validateSingleCommit: true
