name: Pulumi update
on:
  push:
    branches:
      - master
      - dev
    paths:
      - pulumi/**
      - .github/workflows/**
jobs:
  up:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: prod
      url: https://log.skut.in

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install pulumi
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: 3.16.0

      - run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1800
          role-session-name: pulumi-github-deploy
          role-skip-session-tagging: true

      - name: Update infra
        uses: pulumi/actions@v3
        with:
          command: up
          work-dir: pulumi
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
